# ---------------------------------------------------- #
# Note: this file originates in template-action-docker #
# ---------------------------------------------------- #

services:
  # ---- mega-linter ---- #
  lint:
    profiles: ["dev"]
    image: oxsecurity/megalinter-javascript:v6.14.0
    volumes:
      - ./:/tmp/lint
    environment:
      MEGALINTER_CONFIG: .github/linters/.mega-linter.yml
      REPORT_OUTPUT_FOLDER: none
      VALIDATE_ALL_CODEBASE: true

  # ---- readme generator ---- #
  readme:
    profiles: ["dev"]
    image: pandoc/minimal:2.18.0
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml

  # ---- app ---- #
  app:
    profiles: ["app"]
    privileged: true
    build: .
    working_dir: /github/workspace
    volumes:
      - ./:/github/workspace
    env_file:
      - .env
